name: Keep Render Alive Direct

on:
  schedule:
    # Yeh har 14 minute me automatic chalega
    - cron: '*/15 * * * *'
  workflow_dispatch: # Isse aap GitHub dashboard se manually bhi run kar sakte hain

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Direct Ping to Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://renver.onrender.com