name: Keep Render Alive Direct

on:
  schedule:
    # GitHub ke scheduler ko stable rakhne ke liye har 15 minute ka interval
    - cron: '*/15 * * * *'
  workflow_dispatch: # Manual testing ke liye

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Direct Ping to Render API
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://renver.onrender.com)
          echo "Render responded with HTTP Status: $STATUS_CODE"