on:
  schedule:
    - cron: '0,14,28,42 4-15 * * *'
    - cron: '0,14 16 * * *'

  workflow_dispatch:

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Direct Ping to Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://renver.onrender.com